[sender]
dataset_path = './input'

[sender.network]
address = "127.0.0.1"
port = 8080
network_type = "unicast"
interface = ""

[receiver]
output_path = "./output"
dataset_name = "received_data2"
buffer_size = 1048576

[receiver.network]
address = "127.0.0.1"
port = 8080
network_type = "unicast"
interface = ""

[logging]
level = "info"
file_enabled = false
file_path = "./logs/app.log"
